[package]
name = "rust-java-rust"
version = "0.1.0"
authors = ["Krishna Kumar T <krishna.thokala2010@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
jni-sys = "0.3.0"
rucaja = "0.4.5"
jni = "0.11.0"
